config/routes.rb
Soxtest::Application.routes.draw do
  get "sequences/index"

  get "sequences/creating"

   root :to => 'sequences#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  #before_filter :auth, :only => "index" if Rails.env.production?

  def index
  end

  def creating
    const = [ '1', '2', '3', 's' ]
    seq = []
    seq2 = []
    basedir = "#{Rails.root}/public/audio/"

    16.times do
      seq << const[rand(4)]
    end

    seq.each do |a|
      seq2 << "#{basedir}#{a}.wav\s"
    end

    str = seq2.join

    system("sox #{str} #{basedir}res1.wav")
    system("sox -m #{basedir}res1.wav #{basedir}dr.wav #{basedir}composit.wav")

    send_file("#{basedir}composit.wav")
  end

private
   def auth
    name = "test"
    pass = "test"

    authenticate_or_request_with_http_basic() do |n, p|
      n == name &&
        p == pass
    end
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>generate test</title>
  <meta charset="UTF-8" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sequences/create.html.erb
<h1>Sequences#create</h1>
<p>Find me in app/views/sequences/create.html.erb</p>

app/views/sequences/index.html.erb
<h1>サーバーで曲をジェネレートするﾃｽﾄaaa</h1>
<%= link_to "create!!!",sequences_creating_path %>